# FrontierManager config
#
# Name this file <worldname>.yml, where "<worldname>" is the name of the world to manae.
#
# To manage more than one world, just copy this file and name it appropriately for each world
# that needs to be managed.

# Enable or disable management of this world
enabled: true

# seed: The seed that will be used when regenerating the world, set to 0 to use a random seed
seed: 0

# scheduled reset section
#
# Some time values in this section are defined using a human readable time format of
# "<year> <month> <dayOfMonth> <timeOfDay>", timeOfDay being in 24 hour time.  For example:
# - "2015 1 15 00:00" means 15th January 2015
# - "2015 1 15 10:00" means 15th January 2015 at 10am
# - "2015 1 15 14:30" means 15th January 2015 at 2:30pm
# Options that use this format are: lastReset
#
# Other time values in this section are defined using the same human readable time format but using
# relative values instead of absolute ones, so for example:
# - "0 0 15 00:00" means 15 days
# - "0 1 15 00:00" means 1 month and 15 days
# - "0 1 15 12:00" means 1 month, 15 days and 12 hours
# - "0 1 15 12:30" means 1 month, 15 days, 12 hours and 30 minutes
# - "2 1 15 12:30" means 2 years, 1 month, 15 days, 12 hours and 30 minutes
# Options that use this format are: timeToNextReset
schedule:
   
   # lastReset: The date and time the last scheduled reset occurred, the plugin will set this value
   # automatically, however if this is the first time you are setting up this config you should set this
   # value to a date and time in the future of when you want the first scheduled reset to run.
   lastReset: 0 0 0 00:00
   
   # timeToNextReset: Define the time that should pass from the last reset to the next reset.
   # 
   # For example the value "0 1 0 00:00" would cause the reset to happen exactly 1 month from the lastReset
   # time above, or with the value "0 0 15 16:30", the next reset would happen exactly 15 days, 16 hours
   # and 30 minutes from the the lastReset time above.  When the scheduled reset happens the time set
   # here will be added to the lastReset time above to schedule the next reset.
   timeToNextReset: 0 1 0 00:00

# warnChat: Display warnings in chat leading up to the reset
warnChat: true

# warnStorage: Display a warning message to players each time they place a storage container
# e.g. a chest or furnace that this world will be reset and any items will be removed without warning.
warnStorage: true